### ISSUE TITLE
Include stacktrace in event handler and process manager `error` callback functions

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded#303] opened 2019-09-16 10:09 UTC
To assist with debugging exceptions the stacktrace should be included in the failure context struct passed to the event handler and process manager error callback functions. This would allow the user to log the error and the source stacktrace.

**Comment by justgage** [comment] 2019-10-22 02:51
This has been a pretty big pain point, I think I might be one I take on. Basically any time that an event handler crashes it causes a huge error and usually the source of the problem is near the beginning.

**Comment by davydog187** [comment] 2020-02-16 14:48
@justgage @slashdotdash I pushed up a PR here. Please take a look

**Comment by davydog187** [comment] 2020-02-16 14:49
I'm happy to add another to process manager. Note that I did not pass to the callback as it didn't seem necessary.

**Comment by davydog187** [comment] 2020-02-17 13:38
#340 is merged :)

**Comment by davydog187** [comment] 2020-02-17 15:04
Im going to work on a PR for process managers as well. Afterwards a release of commanded would be awesome!

We’re about to put Commanded into production at SimpleBet, and this will be quite helpful for debugging 😅

**Comment by slashdotdash** [comment] 2020-02-17 18:12
@davydog187 I've started work on adding `__STACKTRACE__` to event handler and process manager failure contexts in branch [ent-handler-error-stacktrace](https://github.com/commanded/commanded/tree/feature/event-handler-error-stacktrace). Process managers are slightly more complex than event handlers because they can error when handling an event or when dispatching a command.

**Comment by davydog187** [comment] 2020-02-17 18:50
@slashdotdash great! I didn't start it yet, so if you've got it I won't bother Happy to help though!

**Comment by davydog187** [comment] 2020-02-17 18:53
Took a look at your branch. You know the codebase a million times better than I do. It looks great!

**Closed** 2020-04-30 21:25 UTC
