### ISSUE TITLE
Advice on subscription_already_exists - time out for consitency

### ISSUE THREAD

**Issue by delmendo** [commanded/commanded#338] opened 2020-02-11 03:07 UTC
I'm working on a commanded app. I started from conduit. Instead of authors I have owners.  I setup an aggregate command to create the user, then the owner, and them some folders for the owner. Originally I tried to do it as a workflow the way it is was done in conduit but I kept hitting consistency errors so I changed it to a call in the aggregate to just dispatch multiple commands in sequence. 

I keep hitting problems two errors as I work on the system:

I get a bunch of :subscription_already_exists  and randomly when I run my tests I get a consistency timeout for a user or owner.  

I'm not sure how to troubleshoot or determine where I'm doing the wrong thing. Can you give me advice on where I start looking to determine how I'm triggering the error?

I'll try to get an app together that I can share the code from - but it seems to be timing specific (meaning as more load gets put on my laptop I see the errors happen more often).

[error] GenServer {Jobward.App.LocalRegistry, {Jobward.App, Commanded.Event.Handler, "Jobward.Documents.Projectors.Folder"}} terminating
** (stop) exited in: GenServer.call(#PID<0.1381.0>, {:ack, 64, #PID<0.1375.0>}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
    (commanded) lib/commanded/event/handler.ex:667: Commanded.Event.Handler.ack_event/2
    (commanded) lib/commanded/event/handler.ex:654: Commanded.Event.Handler.confirm_receipt/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/event/handler.ex:493: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "13540d33-e8b6-4e76-9a5e-c851a5de2ca3", correlation_id: "17558d1c-0a7d-47d2-bd7d-33a34eb30dd4", created_at: ~U[2020-02-11 02:57:26.735235Z], data: %Jobward.Accounts.Events.RefreshTokenSaved{expires_at: "2020-03-10T02:57:26Z", is_revoked: false, refresh_token_uuid: "60348165-4e3e-4980-8e3c-52ab27f38480", token: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJKb2J3YXJkIiwiZXhwIjoxNTgzODA5MDQ2LCJpYXQiOjE1ODEzODk4NDYsImlzcyI6IkpvYndhcmQiLCJqdGkiOiI2MDM0ODE2NS00ZTNlLTQ5ODAtOGUzYy01MmFiMjdmMzg0ODAiLCJuYmYiOjE1ODEzODk4NDUsInN1YiI6IlVzZXI6NzNiZWE0OGEtYzM0OS00ODcyLTg4N2QtMzYxOWNkNzYzZjY5IiwidHlwIjoicmVmcmVzaCJ9.d4BZGkK7ruGTqEhOmISOPzrjdPeyI6Nn8O3A1fBJr8AHRq14My06q0FtcJNksYY4d2wv-QXZ4z07vWEv8FH9sA", user_uuid: "73bea48a-c349-4872-887d-3619cd763f69"}, event_id: "c7550c26-f038-464f-839b-1cde23368940", event_number: 64, event_type: "Elixir.Jobward.Accounts.Events.RefreshTokenSaved", metadata: %{}, stream_id: "refresh-token-60348165-4e3e-4980-8e3c-52ab27f38480", stream_version: 1}]}
State: %Commanded.Event.Handler{application: Jobward.App, consistency: :strong, handler_module: Jobward.Documents.Projectors.Folder, handler_name: "Jobward.Documents.Projectors.Folder", last_seen_event: 63, subscribe_from: :origin, subscribe_to: :all, subscription: #PID<0.1381.0>, subscription_ref: #Reference<0.2763056689.4241752065.57467>}
[error] GenServer {Jobward.App.LocalRegistry, {Jobward.App, Commanded.Event.Handler, "Jobward.Documents.Projectors.Folder"}} terminating
** (MatchError) no match of right hand side value: {:error, :subscription_already_exists}
    (commanded) lib/commanded/event/handler.ex:544: Commanded.Event.Handler.subscribe_to_events/1
    (commanded) lib/commanded/event/handler.ex:417: Commanded.Event.Handler.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :subscribe_to_events}
State: %Commanded.Event.Handler{application: Jobward.App, consistency: :strong, handler_module: Jobward.Documents.Projectors.Folder, handler_name: "Jobward.Documents.Projectors.Folder", last_seen_event: nil, subscribe_from: :origin, subscribe_to: :all, subscription: nil, subscription_ref: nil}
[error] GenServer {Jobward.App.LocalRegistry, {Jobward.App, Commanded.Event.Handler, "Jobward.Documents.Projectors.Folder"}} terminating
** (MatchError) no match of right hand side value: {:error, :subscription_already_exists}
    (commanded) lib/commanded/event/handler.ex:544: Commanded.Event.Handler.subscribe_to_events/1
    (commanded) lib/commanded/event/handler.ex:417: Commanded.Event.Handler.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :subscribe_to_events}
State: %Commanded.Event.Handler{application: Jobward.App, consistency: :strong, handler_module: Jobward.Documents.Projectors.Folder, handler_name: "Jobward.Documents.Projectors.Folder", last_seen_event: nil, subscribe_from: :origin, subscribe_to: :all, subscription: nil, subscription_ref: nil}
[error] GenServer {Jobward.App.LocalRegistry, {Jobward.App, Commanded.Event.Handler, "Jobward.Documents.Projectors.Folder"}} terminating
** (MatchError) no match of right hand side value: {:error, :subscription_already_exists}
    (commanded) lib/commanded/event/handler.ex:544: Commanded.Event.Handler.subscribe_to_events/1
    (commanded) lib/commanded/event/handler.ex:417: Commanded.Event.Handler.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :subscribe_to_events}
State: %Commanded.Event.Handler{application: Jobward.App, consistency: :strong, handler_module: Jobward.Documents.Projectors.Folder, handler_name: "Jobward.Documents.Projectors.Folder", last_seen_event: nil, subscribe_from: :origin, subscribe_to: :all, subscription: nil, subscription_ref: nil}
[debug] Subscription "Jobward.Documents.Projectors.Owner"@"$all" subscriber #PID<0.1376.0> down due to: :shutdown
[debug] Subscription "Jobward.Documents.Projectors.Owner"@"$all" has no subscribers, shutting down
[debug] Subscription "Jobward.Documents.Projectors.Owner"@"$all" attempting to connect subscriber #PID<0.1613.0>
[error] GenServer {Jobward.App.LocalRegistry, {Jobward.App, Commanded.Event.Handler, "Jobward.Documents.Projectors.Folder"}} terminating
** (MatchError) no match of right hand side value: {:error, :subscription_already_exists}
    (commanded) lib/commanded/event/handler.ex:544: Commanded.Event.Handler.subscribe_to_events/1
    (commanded) lib/commanded/event/handler.ex:417: Commanded.Event.Handler.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :subscribe_to_events}
State: %Commanded.Event.Handler{application: Jobward.App, consistency: :strong, handler_module: Jobward.Documents.Projectors.Folder, handler_name: "Jobward.Documents.Projectors.Folder", last_seen_event: nil, subscribe_from: :origin, subscribe_to: :all, subscription: nil, subscription_ref: nil}

**Comment by larskluge** [comment] 2020-02-11 12:12
Running into the same error. When the server is busy processing a bunch of other stuff, it takes longer than 5 seconds to ack an event. Restart of event handler is not clean due to `{:error, :subscription_already_exists}` issue. Have no solution nor workaround just yet.

**Comment by larskluge** [comment] 2020-02-11 15:01
I'm using PG-based `EventStore` which seems to have something like a 5s timeout before releasing a subscription (?). However, the first (aweful) fix that worked for me is to overwrite `start_link` and place a timeout of a couple seconds in there.. 

```elixir
  defoverridable start_link: 1
  def start_link(opts) do
    Process.sleep 2_000

    module_opts = Keyword.drop(@opts, [:application, :name])
    opts = Handler.start_opts(__MODULE__, module_opts, opts)

    Handler.start_link(@application, @name, __MODULE__, opts)
  end
```

This works, but is obviously not a solution.

**Comment by slashdotdash** [comment] 2020-02-18 10:30
@larskluge We could add a match on the ` {:error, :subscription_already_exists}` and retry the subscription after a small delay (with back-off).

**Comment by slashdotdash** [comment] 2020-02-20 08:41
I encountered this exact same issue yesterday while testing a local cluster. I will implement a retry strategy and include in the next Commanded v1.0.1 hotfix release.

**Comment by larskluge** [comment] 2020-02-20 10:20
@slashdotdash the retry with delay should do the trick. glad you were able to reproduce it. thanks!

**Comment by slashdotdash** [comment] 2020-02-27 19:49
I've merged PR #348 with subscription retrying for event handlers and process managers into the release v1.0.0 branch. This will be released as v1.0.1 imminently.

**Comment by slashdotdash** [comment] 2020-02-27 19:49
Fixed by #348.

**Closed by slashdotdash** 2020-02-27 19:49 UTC

**Comment by larskluge** [comment] 2020-02-28 09:46
Running v1.0.1 in production since a couple hours now w/ my removed start up delays and the retry seems to work well. Thanks @slashdotdash !

**Comment by slashdotdash** [comment] 2020-02-28 10:20
@larskluge That's good news. Thanks for the update.
